function results = run_case(caseDef, options)
%RUN_CASE V1.5 单工况求解入口。
% 功能说明:
%   维持主接口不变，按固定流程执行：
%   validate_case_struct -> preprocess_case -> solve_equilibrium -> postprocess_results。
%   当 tire.mode='range' 时，自动计算 low/nominal/high 三场景并返回区间结果。
%
% 输入:
%   caseDef - 顶层输入结构体
%   options - 可选控制参数：
%             .solverOverrides (struct)
%             .exportCsv (char/string)
%             .returnOnError (logical)
%
% 输出:
%   results - 统一结果结构体（range 模式含 results.range）

if nargin < 2 || isempty(options)
    options = struct();
end

returnOnError = false;
if isfield(options, 'returnOnError')
    returnOnError = logical(options.returnOnError);
end

try
    % ===== 合并 solver 默认值与覆盖参数 =====
    solverDefault = default_solver_options();
    if ~isfield(caseDef, 'solver') || isempty(caseDef.solver)
        caseDef.solver = solverDefault;
    else
        [caseDef.solver, ~] = ensure_fields(caseDef.solver, solverDefault, true);
    end
    if isfield(options, 'solverOverrides') && isstruct(options.solverOverrides)
        fns = fieldnames(options.solverOverrides);
        for i = 1:numel(fns)
            caseDef.solver.(fns{i}) = options.solverOverrides.(fns{i});
        end
    end

    % ===== 输入校验 =====
    [caseDef, validation] = validate_case_struct(caseDef);
    caseDef.validation = validation;
    emit_validation_warnings(validation, caseDef.solver);
    if validation.badInput
        error('run_case:ValidationFailed', '%s', strjoin(validation.messages, ' | '));
    end

    if strcmpi(caseDef.tire.mode, 'range')
        results = run_tire_range_case(caseDef);
    else
        results = run_single_validated_case(caseDef);
    end

    % ===== 可选导出 =====
    if isfield(options, 'exportCsv') && ~isempty(options.exportCsv)
        export_results_table(results, options.exportCsv);
    end

catch ME
    if ~returnOnError
        rethrow(ME);
    end
    results = build_error_results(caseDef, ME);
end
end

function results = run_tire_range_case(caseDef)
%RUN_TIRE_RANGE_CASE 执行 tire.mode='range' 的 low/nominal/high 三场景求解。

rawRangeInputs = caseDef;
fRange = normalize_triplet(caseDef.tire.ktFrontRange);
rRange = normalize_triplet(caseDef.tire.ktRearRange);
labels = {'low', 'nominal', 'high'};

range = struct();
for i = 1:3
    caseI = caseDef;
    caseI.tire.mode = 'fixed';
    caseI.tire.ktFront = fRange(i);
    caseI.tire.ktRear = rRange(i);
    caseI.meta.name = sprintf('%s__kt_%s', caseDef.meta.name, labels{i});

    resI = run_single_validated_case(caseI);
    resI.tire.mode = 'range';
    resI.tire.ktCaseLabel = labels{i};
    range.(labels{i}) = resI;
end

% 主结果默认返回 nominal；若关闭该策略则返回 low 场景（保守筛选）。
if logical(caseDef.solver.rangeUseNominalAsPrimary)
    results = range.nominal;
    primaryLabel = 'nominal';
else
    results = range.low;
    primaryLabel = 'low';
end

results.meta.name = caseDef.meta.name;
results.meta.version = caseDef.meta.version;
results.inputsRaw = rawRangeInputs;
results.inputsNominal = range.nominal.inputs;

results.tire.mode = 'range';
results.tire.ktCaseLabel = primaryLabel;
results.tire.ktBand = [mean([fRange(1), rRange(1)]), mean([fRange(2), rRange(2)]), mean([fRange(3), rRange(3)])];

results.range = range;
results.range.labels = labels;
results.range.band = struct();
results.range.band.hMin = [range.low.clearance.hMin, range.nominal.clearance.hMin, range.high.clearance.hMin];
results.range.band.hStaticMin = [range.low.clearance.hStaticMin, range.nominal.clearance.hStaticMin, range.high.clearance.hStaticMin];
results.range.band.hDynamicMin = [range.low.clearance.hDynamicMin, range.nominal.clearance.hDynamicMin, range.high.clearance.hDynamicMin];
results.range.band.effectiveTotalTravel = [ ...
    range.low.rules.minEffectiveTotalTravel, ...
    range.nominal.rules.minEffectiveTotalTravel, ...
    range.high.rules.minEffectiveTotalTravel];
results.range.band.staticGroundClearancePass = [ ...
    range.low.rules.staticGroundClearancePass, ...
    range.nominal.rules.staticGroundClearancePass, ...
    range.high.rules.staticGroundClearancePass];
results.range.band.dynamicClearancePass = [ ...
    range.low.targets.dynamicClearancePass, ...
    range.nominal.targets.dynamicClearancePass, ...
    range.high.targets.dynamicClearancePass];
results.range.band.hDynamicMinBumpAdjusted = [ ...
    range.low.clearance.hDynamicMinBumpAdjusted, ...
    range.nominal.clearance.hDynamicMinBumpAdjusted, ...
    range.high.clearance.hDynamicMinBumpAdjusted];
results.range.band.dynamicClearanceBumpAdjustedPass = [ ...
    range.low.clearance.dynamicClearanceBumpAdjustedPass, ...
    range.nominal.clearance.dynamicClearanceBumpAdjustedPass, ...
    range.high.clearance.dynamicClearanceBumpAdjustedPass];
results.range.band.lossPct = [range.low.aero.lossPct, range.nominal.aero.lossPct, range.high.aero.lossPct];
results.range.band.frontShareMigrationPct = [range.low.aero.frontShareMigrationPct, ...
    range.nominal.aero.frontShareMigrationPct, range.high.aero.frontShareMigrationPct];
results.range.band.aeroPlatformPass = [ ...
    range.low.flags.aeroPlatformPass, range.nominal.flags.aeroPlatformPass, range.high.flags.aeroPlatformPass];
results.range.band.scrapePassQuasiStatic = [ ...
    range.low.flags.scrapePassQuasiStatic, range.nominal.flags.scrapePassQuasiStatic, range.high.flags.scrapePassQuasiStatic];
results.range.band.scrapePassBumpAdjusted = [ ...
    range.low.flags.scrapePassBumpAdjusted, range.nominal.flags.scrapePassBumpAdjusted, range.high.flags.scrapePassBumpAdjusted];
results.range.band.mapClassQuasiStatic = [ ...
    range.low.flags.mapClassQuasiStatic, range.nominal.flags.mapClassQuasiStatic, range.high.flags.mapClassQuasiStatic];
results.range.band.mapClassBumpAdjusted = [ ...
    range.low.flags.mapClassBumpAdjusted, range.nominal.flags.mapClassBumpAdjusted, range.high.flags.mapClassBumpAdjusted];
results.range.band.feasible = [range.low.flags.feasible, range.nominal.flags.feasible, range.high.flags.feasible];
results.range.band.rulePass = [range.low.flags.rulePass, range.nominal.flags.rulePass, range.high.flags.rulePass];
results.range.band.designPass = [range.low.flags.designPass, range.nominal.flags.designPass, range.high.flags.designPass];

results.flags.feasibleRangeAll = all(results.range.band.feasible);
results.flags.feasibleRangeAny = any(results.range.band.feasible);
results.flags.rulePassRangeAll = all(results.range.band.rulePass);
results.flags.designPassRangeAll = all(results.range.band.designPass);
end

function results = run_single_validated_case(caseDef)
%RUN_SINGLE_VALIDATED_CASE 对“已通过 validate 的 caseDef”执行主求解流程。

rawInputs = caseDef;
caseDef = preprocess_case(caseDef);
solveOut = solve_equilibrium(caseDef);
results = postprocess_results(caseDef, solveOut);
results = apply_tire_force_layer(caseDef, results);
results.inputsRaw = rawInputs;
end

function results = apply_tire_force_layer(caseDef, results)
%APPLY_TIRE_FORCE_LAYER 在平台求解完成后追加 V1.5 轮胎代理后评估层。
% 关键说明:
%   1) 轮胎代理层严格位于 postprocess_results 之后，不回写主平衡链。
%   2) Fz 来自平台收敛后的 results.corners.FzWheel，而不是用户再次手填。
%   3) 若轮胎层失败，只置位 tireEvalFailed 并 warning，不清空平台主结果。

if ~isfield(caseDef, 'tire') || ~isfield(caseDef.tire, 'forceModel') ...
        || ~logical(caseDef.tire.forceModel.enable)
    return;
end

try
    tireTableData = load_tire_table_data(caseDef);
    tireOpNorm = normalize_tire_operating_points(caseDef, results, tireTableData);
    tireEval = evaluate_tire_table_model(caseDef, tireTableData, tireOpNorm);
    results = postprocess_tire_results(results, caseDef, tireTableData, tireOpNorm, tireEval);
catch ME
    results.flags.tireForceModelEnabled = true;
    results.flags.tireEvalFailed = true;
    results.tire.forceModel.enable = true;
    results.tire.forceModel.sourceType = lower(strtrim(char(string(caseDef.tire.forceModel.sourceType))));
    results.tire.forceModel.mode = lower(strtrim(char(string(caseDef.tire.forceModel.mode))));
    results.tire.forceModel.outOfRangePolicy = lower(strtrim(char(string(caseDef.tire.forceModel.outOfRangePolicy))));
    results.tire.forceModel.includeAligningMoment = logical(caseDef.tire.forceModel.includeAligningMoment);
    results.tire.validity.evalFailed = true;
    results.debug.tireForceModelError = ME.message;
    warning('run_case:TireEvaluationFailed', '%s', ME.message);
end
end

function emit_validation_warnings(validation, solver)
%EMIT_VALIDATION_WARNINGS 将 validation.warnings 以真实 warning 发出。

if ~isfield(solver, 'warnOnDeprecatedInput') || ~logical(solver.warnOnDeprecatedInput)
    return;
end
if ~isfield(validation, 'warnings') || isempty(validation.warnings)
    return;
end

for i = 1:numel(validation.warnings)
    warning('run_case:ValidationWarning', '%s', validation.warnings{i});
end
end

function trip = normalize_triplet(x)
if isempty(x) || ~isnumeric(x)
    error('run_case:BadTireRange', 'tire range must be numeric with 2 or 3 elements.');
end
x = sort(double(x(:)), 'ascend');
if numel(x) == 2
    trip = [x(1); 0.5 * (x(1) + x(2)); x(2)];
elseif numel(x) == 3
    trip = x;
else
    error('run_case:BadTireRangeSize', 'tire range must have 2 or 3 elements.');
end
if any(~isfinite(trip)) || any(trip <= 0)
    error('run_case:BadTireRangeValue', 'tire range values must be finite and positive.');
end
end

function results = build_error_results(caseDef, ME)
%BUILD_ERROR_RESULTS returnOnError=true 时的最小失败结构体。

results = struct();
results.meta = struct('name', 'error_case', 'version', 'V1.5');
if isstruct(caseDef) && isfield(caseDef, 'meta')
    if isfield(caseDef.meta, 'name'); results.meta.name = caseDef.meta.name; end
    if isfield(caseDef.meta, 'version'); results.meta.version = caseDef.meta.version; end
end

results.inputs = caseDef;
results.inputsRaw = caseDef;
results.inputsNominal = struct();

results.state = struct('z', nan, 'theta', nan, 'phi', nan, 'theta_deg', nan, 'phi_deg', nan);
results.loads = struct('Qext', nan(3,1), 'Mpitch', nan, 'Mroll', nan, 'FzAxleFront', nan, 'FzAxleRear', nan);
results.aero = struct('hf', nan, 'hr', nan, 'Cz', nan, 'Cd', nan, 'Fz', nan, 'Drag', nan, ...
    'frontShare', nan, 'rearShare', nan, 'FzFront', nan, 'FzRear', nan, ...
    'lossPct', nan, 'balanceMigrationPct', nan, 'frontShareMigrationPct', nan, ...
    'mapClampedAny', false, 'hfClamped', false, 'hrClamped', false, 'phiClamped', false, ...
    'betaClamped', false, 'interpFallbackUsed', false);
results.tire = struct('mode', 'unknown', 'ktUsed', nan(4,1), 'ktCaseLabel', 'unknown', ...
    'ktBand', nan(1,3), 'tireComplianceIgnored', false, 'groundMetricConfidence', 'unknown');
results.tire.forceModel = struct('enable', false, 'sourceType', '', 'mode', '', ...
    'outOfRangePolicy', '', 'includeAligningMoment', false, 'sourceFile', '', 'dataSummary', struct());
results.tire.inputs = struct('cornerOrder', {{'FL';'FR';'RL';'RR'}}, ...
    'alpha', nan(4,1), 'alphaDeg', nan(4,1), 'kappa', nan(4,1), ...
    'gamma', nan(4,1), 'gammaDeg', nan(4,1), 'pressure', nan(4,1), 'Fz', nan(4,1), ...
    'sourceType', '', 'mode', '', 'outOfRangePolicy', '', 'dataSummary', '', 'meta', struct());
results.tire.forces = struct('Fx', nan(4,1), 'Fy', nan(4,1), 'Mz', nan(4,1), ...
    'FxRequested', nan(4,1), 'FyRequested', nan(4,1), 'FxCap', nan(4,1), 'FyCap', nan(4,1));
results.tire.coeff = struct('muX', nan(4,1), 'muY', nan(4,1), 'maxAbsMuX', nan, 'maxAbsMuY', nan);
results.tire.balance = struct('FyFrontTotal', nan, 'FyRearTotal', nan, ...
    'FxFrontTotal', nan, 'FxRearTotal', nan, 'frontFyShare', nan, 'rearFyShare', nan, ...
    'frontUtilization', nan, 'rearUtilization', nan, 'balanceIndex', nan, ...
    'peakMarginFront', nan, 'peakMarginRear', nan, 'conditionType', strings(4,1), ...
    'usedCombinedProxyAny', false, 'usedCombinedTableAny', false);
results.tire.validity = struct('validFz', false(4,1), 'validAlpha', false(4,1), ...
    'validKappa', false(4,1), 'validGamma', false(4,1), ...
    'outOfRange', false(4,1), 'outOfRangeAny', false, ...
    'contactLost', false(4,1), 'contactLostAny', false, ...
    'evalFailed', true, 'wasClipped', false(4,1));
results.tire.scan = struct('enable', false, 'field', '', 'applyMode', '', 'unit', '', ...
    'valuesRaw', zeros(0,1), 'valuesSI', zeros(0,1), ...
    'Fx', zeros(4,0), 'Fy', zeros(4,0), 'Mz', zeros(4,0), ...
    'muX', zeros(4,0), 'muY', zeros(4,0), ...
    'utilization', zeros(4,0), 'peakMargin', zeros(4,0), ...
    'FyFrontTotal', zeros(1,0), 'FyRearTotal', zeros(1,0), ...
    'FxFrontTotal', zeros(1,0), 'FxRearTotal', zeros(1,0), ...
    'balanceIndex', zeros(1,0), 'contactLostAny', false(1,0), ...
    'outOfRangeAny', false(1,0), 'cornerNames', {{'FL';'FR';'RL';'RR'}});
results.corners = struct('names', {{'FL';'FR';'RL';'RR'}}, ...
    'deltaGround', nan(4,1), 'deltaSuspWheel', nan(4,1), 'deltaTire', nan(4,1), ...
    'deltaWheel', nan(4,1), 'delta', nan(4,1), 'wheelJounce', nan(4,1), 'wheelDroop', nan(4,1), ...
    'effectiveJounce', nan(4,1), 'effectiveDroop', nan(4,1), 'effectiveTotalTravel', nan(4,1), ...
    'wheelJounceUsagePct', nan(4,1), 'wheelDroopUsagePct', nan(4,1), ...
    'shockStroke', nan(4,1), 'shockCurrentUsed', nan(4,1), ...
    'shockCompMargin', nan(4,1), 'shockReboundMargin', nan(4,1), ...
    'shockPositionPct', nan(4,1), 'shockStaticPositionPct', nan(4,1), ...
    'shockBiasFromMidPct', nan(4,1), 'shockDynamicStrokePct', nan(4,1), ...
    'shockCompUsagePct', nan(4,1), 'shockReboundUsagePct', nan(4,1), ...
    'Ftotal', nan(4,1), 'Fmain', nan(4,1), 'FzStatic', nan(4,1), 'FzTotal', nan(4,1), 'FzWheel', nan(4,1), ...
    'wheelJounceViolation', false(4,1), 'wheelDroopViolation', false(4,1), ...
    'shockCompViolation', false(4,1), 'shockReboundViolation', false(4,1), ...
    'tireDeflection', nan(4,1));
results.clearance = struct( ...
    'names', {{}}, ...
    'hAll', [], 'hMin', nan, 'hMinName', '', ...
    'hStaticAll', [], 'hStaticMin', nan, 'hStaticMinName', '', ...
    'hDynamicAll', [], 'hDynamicMin', nan, 'hDynamicMinName', '', ...
    'hDynamicAllBumpAdjusted', [], 'hDynamicMinBumpAdjusted', nan, ...
    'hDynamicMinBumpAdjustedName', '', ...
    'dynamicClearanceBumpAdjustedPass', false, ...
    'dynamicClearanceBumpAdjustedMargin', nan, ...
    'bumpReserveByPoint', []);
results.platform = struct( ...
    'clearanceNames', {{}}, ...
    'clearanceValues', [], ...
    'clearanceStaticValues', [], ...
    'clearanceDynamicValues', [], ...
    'clearanceBumpAdjustedValues', [], ...
    'hMin', nan, 'hMinName', '', ...
    'hStaticMin', nan, 'hStaticMinName', '', ...
    'hDynamicMin', nan, 'hDynamicMinName', '', ...
    'hDynamicMinBumpAdjusted', nan, 'hDynamicMinBumpAdjustedName', '', ...
    'hf', nan, 'hr', nan);
results.rules = struct('ruleSet', '', 'enforceRules', false, ...
    'staticGroundClearancePass', false, 'usableWheelTravelPass', false, 'minJouncePass', false, ...
    'rulePassRaw', false, 'rulePass', false, ...
    'staticGroundClearanceMargin', nan, 'usableWheelTravelMargin', nan, 'jounceMargin', nan, ...
    'effectiveJounce', nan(4,1), 'effectiveDroop', nan(4,1), 'effectiveTotalTravel', nan(4,1), ...
    'minEffectiveJounce', nan, 'minEffectiveDroop', nan, 'minEffectiveTotalTravel', nan);
results.targets = struct('enforceTargets', false, ...
    'dynamicClearancePass', false, 'pitchPass', false, 'rollPass', false, ...
    'aeroLossPass', false, 'frontShareMigrationPass', false, ...
    'designPassRaw', false, 'designPass', false, ...
    'dynamicClearanceMargin', nan, 'pitchMargin', nan, 'rollMargin', nan, ...
    'aeroLossMargin', nan, 'frontShareMigrationMargin', nan);
results.metrics = struct('rollGradient_deg_per_g', nan, 'pitchGradient_deg_per_g', nan, ...
    'frontLoadShareDynamic', nan, 'rearLoadShareDynamic', nan, 'dF_LR_front', nan, 'dF_LR_rear', nan, ...
    'maxWheelJounceUsagePct', nan, 'maxWheelDroopUsagePct', nan, ...
    'maxShockCompUsagePct', nan, 'maxShockReboundUsagePct', nan, ...
    'minShockCompMargin', nan, 'minShockReboundMargin', nan, ...
    'maxShockPositionPct', nan, 'maxShockDynamicStrokePct', nan, ...
    'shockStaticPositionPct', nan, 'shockBiasFromMidPct', nan, ...
    'hStaticMin', nan, 'hDynamicMin', nan, 'hDynamicMinBumpAdjusted', nan, ...
    'minEffectiveJounce', nan, 'minEffectiveDroop', nan, 'minEffectiveTotalTravel', nan, ...
    'bumpReserveFront', nan, 'bumpReserveRear', nan, ...
    'balanceIndex', nan, 'peakMarginFront', nan, 'peakMarginRear', nan, ...
    'maxAbsMuX', nan, 'maxAbsMuY', nan);
results.flags = struct('converged', false, 'rulePass', false, 'designPass', false, 'feasible', false, ...
    'wheelJounceViolationAny', false, 'wheelDroopViolationAny', false, ...
    'shockCompViolationAny', false, 'shockReboundViolationAny', false, ...
    'travelViolationAny', false, 'clearanceViolation', false, 'bumpAdjustedClearanceViolation', false, ...
    'tireComplianceIgnored', false, 'groundReferencedLowConfidence', false, ...
    'shockWheelConsistencyWarning', false, 'deltaReconWarning', false, ...
    'mapClampedAny', false, 'mapClamped', false, 'hfClamped', false, 'hrClamped', false, ...
    'phiClamped', false, 'betaClamped', false, 'interpFallbackUsed', false, ...
    'aeroPlatformPass', false, 'scrapePassQuasiStatic', false, 'scrapePassBumpAdjusted', false, ...
    'mapClassQuasiStatic', nan, 'mapClassQuasiStaticLabel', "", 'mapClassQuasiStaticColor', nan(1,3), ...
    'mapClassBumpAdjusted', nan, 'mapClassBumpAdjustedLabel', "", 'mapClassBumpAdjustedColor', nan(1,3), ...
    'tireForceModelEnabled', false, 'tireEvalFailed', true, 'tireOutOfRange', false, ...
    'contactLostAny', false, 'badInput', true);
results.debug = struct('iterHistory', [], 'residualHistory', [], 'lastResidual', nan(3,1), ...
    'message', ME.message, 'solverUsed', 'error', 'mapClampInfo', struct(), ...
    'validation', struct('deltaReconError', nan(4,1), 'deltaReconTol', nan, ...
    'deltaGroundGeom', nan(4,1), 'deltaGroundReconstructed', nan(4,1), ...
    'wheelJounceFromShock', nan(4,1), 'wheelDroopFromShock', nan(4,1), ...
    'bumpReserveByPoint', nan(0,1)));
end
