function caseDef = build_case_2025_baseline()
%BUILD_CASE_2025_BASELINE 构建 V1.5 基线案例输入。
% 功能说明:
%   生成可直接用于 run_case 的标准 baseline caseDef。
%   本文件的目标是：
%   1) 显式写出当前正式使用的输入字段；
%   2) 不依赖 validate_case_struct 的 autofill warning 才成立；
%   3) 不再把 sus.kt 作为正式轮胎输入。
%
% 输入:
%   无
%
% 输出:
%   caseDef - 标准输入结构体
%
% 关键物理假设:
%   1) V1.5 仍维持三自由度准静态平台模型定位
%   2) bump/droop 附加力不回到主求解
%   3) 轮胎柔度通过 tire.mode 管理，轮胎横纵向代理通过 tire.forceModel/tireOp 管理
%
% 单位约定:
%   全部使用 SI（m, kg, N, rad, m/s, m/s^2）

cfgDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(cfgDir);
dataDir = fullfile(rootDir, 'data', 'aero');

% ===== 标准 case 显式输入 =====
% 说明:
%   1) 标准 case 优先显式给出当前活跃字段，减少后续版本调试歧义。
%   2) sus.kt / kBump / bumpGap / kDroop / droopGap 仅保留在兼容层，不再写入正式 case。
%   3) lf/lr 与 kw 在本文件中显式派生，避免标准 case 运行时依赖 autofill warning。
L = 1.58;
wfStatic = 0.46;
lf = (1 - wfStatic) * L;
lr = wfStatic * L;

ksBase = [38000; 38000; 42000; 42000];
mrBase = [0.90; 0.90; 0.92; 0.92];

[mapDataFallback, nominalFallback] = aero_lookup_tables();

% 优先尝试读取 MAT（若不存在或不合法则回退到占位 map）。
% 加载状态必须随 case 传递，禁止把 fallback 静默伪装成已加载数据。
mapData = mapDataFallback;
matPath = fullfile(dataDir, 'aero_map_baseline.mat');
mapLoadStatus = 'fallback_missing';
mapLoadMessage = sprintf('Aero map file not found: %s', matPath);
if exist(matPath, 'file')
    try
        S = load(matPath);
        if isfield(S, 'mapData') && isstruct(S.mapData)
            mapData = S.mapData;
            mapLoadStatus = 'loaded';
            mapLoadMessage = '';
        else
            mapLoadStatus = 'fallback_invalid';
            mapLoadMessage = 'MAT file does not contain a struct named mapData.';
        end
    catch ME
        mapLoadStatus = 'fallback_error';
        mapLoadMessage = ME.message;
    end
end

% 优先读取 CSV 名义参考
nominalRef = nominalFallback;
csvPath = fullfile(dataDir, 'aero_nominal_curve.csv');
nominalLoadStatus = 'fallback_missing';
nominalLoadMessage = sprintf('Aero nominal-reference file not found: %s', csvPath);
if exist(csvPath, 'file')
    try
        T = readtable(csvPath);
        requiredVariables = {'V_mps', 'FzNominal_N', 'frontShareNominal'};
        if ~all(ismember(requiredVariables, T.Properties.VariableNames))
            error('build_case_2025_baseline:InvalidNominalReference', ...
                'Nominal-reference CSV is missing one or more required columns.');
        end
        nominalRef = struct();
        nominalRef.VGrid = T.V_mps;
        nominalRef.FzNominal = T.FzNominal_N;
        nominalRef.frontShareNominal = T.frontShareNominal;
        nominalLoadStatus = 'loaded';
        nominalLoadMessage = '';
    catch ME
        nominalLoadStatus = 'fallback_error';
        nominalLoadMessage = ME.message;
    end
end

caseDef = struct();

caseDef.meta = struct( ...
    'name', 'FS_Baseline_2025', ...
    'version', 'V1.5', ...
    'description', 'Baseline quasi-static suspension-aero platform case', ...
    'author', 'Codex', ...
    'date', char(datetime('today', 'Format', 'yyyy-MM-dd')), ...
    'notes', 'V1.5 continuous upgrade from V1.0.4 with tire proxy, operating point normalization, and balance assessment');

% 车辆参数
caseDef.veh = struct( ...
    'm', 260.0, ...
    'g', 9.81, ...
    'L', L, ...
    'wf_static', wfStatic, ...
    'lf', lf, ...
    'lr', lr, ...
    'tf', 1.24, ...
    'tr', 1.20, ...
    'hCG', 0.270, ...
    'hRCf', 0.030, ...
    'hRCr', 0.050);

% 悬架参数（角点顺序固定为 [FL FR RL RR]）
% 说明:
%   1) 当前正式语义中，轮胎刚度归属 tire.*，而不是 sus.kt。
%   2) kw 在标准 case 中显式给出，便于接口检查；主求解仍保持当前框架语义。
caseDef.sus = struct( ...
    'ks', ksBase, ...
    'mr', mrBase, ...
    'kw', [], ...
    'jounceMax', [0.045; 0.045; 0.050; 0.050], ...
    'droopMax', [0.030; 0.030; 0.035; 0.035], ...
    'shockLenExtended', [0.312; 0.312; 0.328; 0.328], ...
    'shockLenCompressed', [0.248; 0.248; 0.262; 0.262], ...
    'shockLenStatic', [0.286; 0.286; 0.300; 0.300], ...
    'kArbF', 2600, ...
    'kArbR', 2200);

% 轮胎柔度模式（V1.0.4 延续）
% 默认 off：保持与 V1.0.2 一致的“悬架侧趋势”解。
caseDef.tire = struct( ...
    'mode', 'off', ...
    'ktFront', 210000, ...
    'ktRear', 230000, ...
    'ktFrontRange', [180000, 210000, 240000], ...
    'ktRearRange', [200000, 230000, 260000], ...
    'notes', 'off mode baseline for suspension-side trend; switch to fixed/range for ground-referenced studies', ...
    'forceModel', struct( ...
        'enable', false, ...
        'sourceType', 'table_struct', ...
        'file', '', ...
        'data', struct(), ...
        'mode', 'pure_plus_combined_proxy', ...
        'outOfRangePolicy', 'warn_clamp', ...
        'includeAligningMoment', true, ...
        'alphaUnit', 'deg', ...
        'gammaUnit', 'deg', ...
        'kappaUnit', 'ratio', ...
        'FzUnit', 'N', ...
        'forceUnit', 'N', ...
        'momentUnit', 'N*m', ...
        'pressureUnit', 'Pa', ...
        'combinedProxy', struct( ...
            'enable', true, ...
            'type', 'friction_ellipse', ...
            'exponent', 2.0, ...
            'useSeparateBrakeTraction', true)));

% 轮胎 operating point 输入层显式写出，保持标准 case warning-clean。
caseDef.tireOp = struct( ...
    'mode', 'proxy', ...
    'alpha', 0.0, ...
    'kappa', 0.0, ...
    'gamma', 0.0, ...
    'pressure', 83000, ...
    'alphaUnit', 'rad', ...
    'gammaUnit', 'rad', ...
    'kappaUnit', 'ratio', ...
    'pressureUnit', 'Pa', ...
    'alphaFront', 0.050, ...
    'alphaRear', 0.030, ...
    'kappaFront', 0.0, ...
    'kappaRear', 0.0, ...
    'gammaStatic', [-0.035; -0.035; -0.020; -0.020], ...
    'camberGainSusp', [0.20; 0.20; 0.12; 0.12], ...
    'camberGainRoll', [-0.80; 0.80; -0.45; 0.45], ...
    'toeStatic', [0.002; -0.002; 0.001; -0.001], ...
    'scan', struct( ...
        'enable', false, ...
        'field', '', ...
        'values', [], ...
        'unit', '', ...
        'applyMode', 'all_corners', ...
        'notes', 'Set enable=true to request tire scan output in results.tire.scan'));

% 赛规约束及条款来源：
%   - 30 mm 静态离地间隙来自 FSG 2026 v1.1 T2.2.1；
%   - 50 mm usable wheel travel 与驾驶员坐入时 25 mm minimum jounce 来自 T2.5.1。
% 注意：此处只声明 FSG 2026，不能在未取得官方原文时自动等同为 FSC 2026。
caseDef.rules = struct( ...
    'ruleSet', 'FSG_2026_v1.1', ...
    'minStaticGroundClearance', 0.030, ...
    'minUsableWheelTravelTotal', 0.050, ...
    'minJounce', 0.025, ...
    'staticGroundClearanceSource', 'https://www.formulastudent.de/fileadmin/user_upload/all/2026/rules/FS-Rules_2026_v1.1.pdf', ...
    'staticGroundClearanceClause', 'T2.2.1', ...
    'staticGroundClearanceEvidenceStatus', 'verified_public_rule', ...
    'travelConstraintSource', 'https://www.formulastudent.de/fileadmin/user_upload/all/2026/rules/FS-Rules_2026_v1.1.pdf', ...
    'travelConstraintClause', 'T2.5.1', ...
    'travelEvidenceStatus', 'verified_public_rule', ...
    'enforceRules', true);

% 工程目标层（V1.0.4：动态离地高 + 姿态/气动窗口）
caseDef.targets = struct( ...
    'minDynamicClearance', 0.005, ...
    'maxPitchDeg', 3.0, ...
    'maxRollDeg', 4.0, ...
    'maxAeroLossPct', 30.0, ...
    'maxFrontShareMigrationPct', 8.0, ...
    'enforceTargets', true);

% 纵向几何修正系数
caseDef.longi = struct( ...
    'antiDiveF', 0.30, ...
    'antiLiftR', 0.15, ...
    'antiSquatR', 0.35, ...
    'brakeBiasF', 0.58, ...
    'driveBiasR', 1.00);

% bump-adjusted clearance 保守修正（V1.0.4 新增）
caseDef.bumpAdjust = struct( ...
    'enable', false, ...
    'reserveFront', 0.0, ...
    'reserveRear', 0.0, ...
    'notes', 'Conservative bump reserve used only for robustness screening, not transient solving');

% 气动参数
caseDef.aero = struct();
caseDef.aero.rho = 1.225;
caseDef.aero.Aref = 1.20;
caseDef.aero.mapType = 'table_lookup';
caseDef.aero.mapData = mapData;
caseDef.aero.nominalRef = nominalRef;
caseDef.aero.hDrag = 0.120;
caseDef.aero.evidenceStatus = 'synthetic_demo';
caseDef.aero.mapSource = matPath;
caseDef.aero.nominalSource = csvPath;
caseDef.aero.mapLoadStatus = mapLoadStatus;
caseDef.aero.mapLoadMessage = mapLoadMessage;
caseDef.aero.nominalLoadStatus = nominalLoadStatus;
caseDef.aero.nominalLoadMessage = nominalLoadMessage;

% 参考量
caseDef.ref = struct();
caseDef.ref.xAeroF = 0.46;
caseDef.ref.xAeroR = -0.52;
caseDef.ref.hAeroF0 = 0.030;
caseDef.ref.hAeroR0 = 0.040;
caseDef.ref.xClear = [0.70; 0.35; 0.00; -0.35; -0.70];
caseDef.ref.yClear = [0.00; 0.00; 0.00; 0.00; 0.00];
caseDef.ref.hClear0 = [0.030; 0.028; 0.025; 0.028; 0.032];
caseDef.ref.nameClear = {'front_edge'; 'front_floor'; 'mid_floor'; 'rear_floor'; 'diff_exit'};

% 工况
caseDef.man = struct( ...
    'V', 22.0, ...
    'ax', 0.0, ...
    'ay', 8.0, ...
    'beta', 0.0, ...
    'mode', 'cornering', ...
    'description', 'Baseline left corner', ...
    'tag', '2025_base_corner');

caseDef.solver = default_solver_options();
end
